renode_dependencies:
  Fedora:
    - mono-complete
    - polkit
    - gtk2
    - screen
    #- uml-utilities  # Does not exist (alternative?)
    - gtk-sharp2
    - glibc-devel
    - gcc
    - python3
    - python3-pip
