audio_packages:
  Archlinux:
    - gst-plugin-pipewire
    - pipewire
    - pipewire-alsa
    - pipewire-jack
    - pipewire-pulse
    - wireplumber
    - sof-firmware  # TODO: This is only for intel right?
  Fedora:
    - pipewire
    - pipewire-alsa
    - pipewire-gstreamer
    # - pipewire-plugin-jack  # results in conflict?
    - pipewire-pulseaudio
    - wireplumber
