neovim_build_dependencies: {
  Archlinux: [
    base-devel,
    cmake,
    curl,
    git,
    ninja,
    tree-sitter,
    unzip
  ],
  Fedora: [
    autoconf,
    automake,
    cmake,
    curl,
    gcc,
    gcc-c++,
    gettext,
    git,
    libtool,
    make,
    ninja-build,
    patch,
    pkgconfig,
    unzip
  ]
  }
